/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oldmoneyaesthetic.views;

import com.oldmoneyaesthetic.controllers.BinarySearchTableData;
import com.oldmoneyaesthetic.controllers.MergeSortTable;
import com.oldmoneyaesthetic.models.OldMoneyAestheticModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pabishabhatta
 */
public class OldMoneyAesthetic extends javax.swing.JFrame {
    ArrayList<OldMoneyAestheticModel> clothingList = new ArrayList();

    /**
     * Creates new form OldMoneyAesthetic
     */
    public OldMoneyAesthetic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OldMoneyAesthetic_table = new javax.swing.JTable();
        lblSN = new javax.swing.JLabel();
        tf_sn = new javax.swing.JTextField();
        lblClothing = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblDesign = new javax.swing.JLabel();
        lblDesignerName = new javax.swing.JLabel();
        lblFabric = new javax.swing.JLabel();
        lblOccassion = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        tf_clothing = new javax.swing.JTextField();
        tf_brand = new javax.swing.JTextField();
        tf_size = new javax.swing.JTextField();
        tf_color = new javax.swing.JTextField();
        tf_design = new javax.swing.JTextField();
        tf_designername = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        tf_occasion = new javax.swing.JTextField();
        tf_fabric = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonSort = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        sortcolumn = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(151, 90, 90));

        jLabel1.setText("Old Money Aesthetic");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        OldMoneyAesthetic_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Pant", "Calvin Klein", "M", "wide leg", "Pacifico", "44", "Francisco Costa", "Every season", "Cotton"},
                {"2", "Skirt", "Rahlp Lauren", "L", "Ruffled", "Neutral", "4388", "Moda Operandi", "Fall/Winter", "Mulberry Silk"},
                {"3", "Sweater", "H&M", "S", "Turtleneck", "Black", "39", "Sonia Rykiel", "Sleeve dress", "Cable-knit"},
                {"4", "Blazer", "Blenin", "XXL", "Old money notched", "Blue", "9692", "Miss Art Garments", "Every season", "Woven"},
                {"5", "Jacket", "Saint Laurent", "XL", "Denim style", "Black", "1200", "Roger Henri Vivier", "Fall/Winter", "Cotton and Curpo Lining"}
            },
            new String [] {
                "S.N.", "Clothing", "Brand", "Size", "Design", "Color", "Price", "Designer Name", "Occasion", "Fabric"
            }
        ));
        OldMoneyAesthetic_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OldMoneyAesthetic_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OldMoneyAesthetic_table);
        if (OldMoneyAesthetic_table.getColumnModel().getColumnCount() > 0) {
            OldMoneyAesthetic_table.getColumnModel().getColumn(0).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(1).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(2).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(3).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(4).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(5).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(6).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(7).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(8).setResizable(false);
            OldMoneyAesthetic_table.getColumnModel().getColumn(9).setResizable(false);
        }

        lblSN.setBackground(new java.awt.Color(255, 204, 255));
        lblSN.setText("S.N");

        tf_sn.setBackground(new java.awt.Color(255, 153, 204));
        tf_sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_snActionPerformed(evt);
            }
        });

        lblClothing.setBackground(new java.awt.Color(255, 204, 255));
        lblClothing.setText("Clothing");

        lblBrand.setBackground(new java.awt.Color(255, 204, 255));
        lblBrand.setText("Brand");

        lblSize.setBackground(new java.awt.Color(255, 204, 255));
        lblSize.setText("Size");

        lblDesign.setText("Design");

        lblDesignerName.setText("Designer Name");

        lblFabric.setText("Fabric");

        lblOccassion.setText("Occassion");

        lblColor.setText("Color");

        lblPrice.setText("Price");

        tf_clothing.setBackground(new java.awt.Color(255, 153, 204));
        tf_clothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_clothingActionPerformed(evt);
            }
        });

        tf_brand.setBackground(new java.awt.Color(255, 153, 204));

        tf_size.setBackground(new java.awt.Color(255, 153, 204));

        tf_color.setBackground(new java.awt.Color(255, 153, 204));
        tf_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_colorActionPerformed(evt);
            }
        });

        tf_design.setBackground(new java.awt.Color(255, 153, 204));

        tf_designername.setBackground(new java.awt.Color(255, 153, 204));

        tf_price.setBackground(new java.awt.Color(255, 153, 204));

        tf_occasion.setBackground(new java.awt.Color(255, 153, 204));
        tf_occasion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_occasionActionPerformed(evt);
            }
        });

        tf_fabric.setBackground(new java.awt.Color(255, 153, 204));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSort.setText("Sort");
        jButtonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        sortcolumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S.N.", "Clothing", "Brand", "Size", "Design", "Color", "Price", "Designer Name", "Occasion", "Fabric" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S.N.", "Clothing", "Brand", "Size", "Design", "Color", "Price", "Designer Name", "Occasion", "Fabric" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClothing, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(tf_fabric, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblColor)
                                        .addGap(108, 108, 108))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPrice)
                                        .addGap(109, 109, 109)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sortcolumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblOccassion)
                                                    .addComponent(lblDesignerName))
                                                .addGap(49, 49, 49)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_designername, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_occasion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonSort, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBrand)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDesign, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblFabric, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_size, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_design, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_clothing, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(tf_sn))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSN)
                                    .addComponent(tf_sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_clothing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblClothing))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_designername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDesignerName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBrand)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tf_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_occasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOccassion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSize))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_fabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFabric))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSort, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortcolumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_snActionPerformed
       
    }//GEN-LAST:event_tf_snActionPerformed

    private void tf_clothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_clothingActionPerformed
     
    }//GEN-LAST:event_tf_clothingActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
                                           
                                         
    getAllTableData();
    
    String searchValue = jTextField1.getText();

    
    String selectedColumns = (String) jComboBox2.getSelectedItem();

   
    MergeSortTable merge = new MergeSortTable();
    merge.sortArrayList(clothingList, selectedColumns);

   
    BinarySearchTableData binary = new BinarySearchTableData();
    OldMoneyAestheticModel result = binary.binarySearch(clothingList, selectedColumns, searchValue);

    
    if (result != null) {
        StringBuilder resultInfo = new StringBuilder();
        resultInfo.append("Clothing: ").append(result.getClothing()).append("\n")
                .append("Brand: ").append(result.getBrand()).append("\n")
                .append("S.N.: ").append(result.getSn()).append("\n")
                .append("Size: ").append(result.getSize()).append("\n")
                .append("Design: ").append(result.getDesign()).append("\n")
                .append("Color: ").append(result.getColor()).append("\n")
                .append("Price: ").append(result.getPrice()).append("\n")
                .append("Designer Name: ").append(result.getDesigner()).append("\n")
                .append("Occasion: ").append(result.getOccasion()).append("\n")
                .append("Fabric: ").append(result.getFabric()).append("\n");
        JOptionPane.showMessageDialog(null,
                resultInfo.toString(), "Search Result",
                JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, " SEARCH RESULT IS NOT FOUND");
    }
    
    
    
    
    
    
    
    

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
try {
    String color_c = tf_color.getText();
    String design_d = tf_design.getText();
    String size_s = tf_size.getText();
    String brand_b = tf_brand.getText();
    String clothing_c = tf_clothing.getText();
    String designer_d = tf_designername.getText();
    String occasion_o = tf_occasion.getText();
    String fabric_f = tf_fabric.getText();

    String priceText = tf_price.getText();
    String snText = tf_sn.getText();

   
    if (color_c.isEmpty() || design_d.isEmpty() || size_s.isEmpty() || brand_b.isEmpty() || clothing_c.isEmpty() ||
            designer_d.isEmpty() || occasion_o.isEmpty() || fabric_f.isEmpty() || priceText.isEmpty() || snText.isEmpty()) {
       
        JOptionPane.showMessageDialog(null, "Please fill in all the fields.");
    } else {
        int price_p = Integer.parseInt(priceText);
        int sn_s = Integer.parseInt(snText);

       
        if (price_p < 0 || sn_s < 0) {
            
            JOptionPane.showMessageDialog(null, "Invalid input for Price or S.N. Please enter positive integers.");
        } else {
           
            OldMoneyAestheticModel mymodelclass = new OldMoneyAestheticModel(sn_s, clothing_c, brand_b, size_s, design_d, color_c, price_p, designer_d, occasion_o, fabric_f);

          
            DefaultTableModel myAdd = (DefaultTableModel) OldMoneyAesthetic_table.getModel();
            myAdd.addRow(new Object[]{sn_s, clothing_c, brand_b, size_s, design_d, color_c, price_p, designer_d, occasion_o, fabric_f});

          
            clothingList.add(mymodelclass);

            JOptionPane.showMessageDialog(null, "Your new data has been added in the Table");
        }
    }
} catch (NumberFormatException e) {
    
    JOptionPane.showMessageDialog(null, "Invalid input for Price or S.N. Please enter valid integers.");
}


// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void tf_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_colorActionPerformed
     
    }//GEN-LAST:event_tf_colorActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) OldMoneyAesthetic_table.getModel();
int selectedRow = OldMoneyAesthetic_table.getSelectedRow();

if (selectedRow == -1) {
    if (OldMoneyAesthetic_table.getRowCount() == 4) {
        JOptionPane.showMessageDialog(null, "Your table is empty", "Please check", JOptionPane.QUESTION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No row is selected", "Please check", JOptionPane.QUESTION_MESSAGE);
    }
} else {
    model.removeRow(selectedRow);
    clothingList.remove(selectedRow);
            JOptionPane.showMessageDialog(null, "The following row has been deleted", "Hello user", JOptionPane.QUESTION_MESSAGE);

    tf_sn.setText("");
        tf_clothing.setText("");
        tf_brand.setText("");
        tf_size.setText("");
        tf_design.setText("");
        tf_color.setText("");
        tf_price.setText("");
        tf_designername.setText("");
        tf_occasion.setText("");
        tf_fabric.setText("");

}
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void OldMoneyAesthetic_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OldMoneyAesthetic_tableMouseClicked
        
        DefaultTableModel Model = (DefaultTableModel) OldMoneyAesthetic_table.getModel ();
        String tbl_sn = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 0).toString();
        String tbl_clothing = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 1).toString();
        String tbl_brand = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 2).toString();
        String tbl_size = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 3).toString();
        String tbl_design = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 4).toString();
        String tbl_color = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 5).toString();
        String tbl_price = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 6).toString();
        String tbl_designername = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 7).toString();
        String tbl_occassion = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 8).toString();
        String tbl_fabric = Model.getValueAt (OldMoneyAesthetic_table.getSelectedRow(), 9).toString();

        tf_sn.setText(tbl_sn);
        tf_clothing.setText(tbl_clothing);
        tf_brand.setText(tbl_brand);
        tf_size.setText(tbl_size);
        tf_design.setText(tbl_design);
        tf_color.setText(tbl_color);
        tf_price.setText(tbl_price);
        tf_designername.setText(tbl_designername);
        tf_occasion.setText(tbl_occassion);
        tf_fabric.setText(tbl_fabric);

    }//GEN-LAST:event_OldMoneyAesthetic_tableMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
                                        
    getAllTableData();
    DefaultTableModel model = (DefaultTableModel) OldMoneyAesthetic_table.getModel();

    if (OldMoneyAesthetic_table.getSelectedRow() == 4) {
        String tbl_sn = tf_sn.getText();
        String tbl_clothing = tf_clothing.getText();
        String tbl_brand = tf_brand.getText();
        String tbl_size = tf_size.getText();
        String tbl_design = tf_design.getText();
        String tbl_color = tf_color.getText();
        String tbl_price = tf_price.getText();
        String tbl_designername = tf_designername.getText();
        String tbl_occassion = tf_occasion.getText();
        String tbl_fabric = tf_fabric.getText();

        model.setValueAt(tbl_sn, OldMoneyAesthetic_table.getSelectedRow(), 0);
        model.setValueAt(tbl_clothing, OldMoneyAesthetic_table.getSelectedRow(), 1);
        model.setValueAt(tbl_brand, OldMoneyAesthetic_table.getSelectedRow(), 2);
        model.setValueAt(tbl_size, OldMoneyAesthetic_table.getSelectedRow(), 3);
        model.setValueAt(tbl_design, OldMoneyAesthetic_table.getSelectedRow(), 4);
        model.setValueAt(tbl_color, OldMoneyAesthetic_table.getSelectedRow(), 5);
        model.setValueAt(tbl_price, OldMoneyAesthetic_table.getSelectedRow(), 6);
        model.setValueAt(tbl_designername, OldMoneyAesthetic_table.getSelectedRow(), 7);
        model.setValueAt(tbl_occassion, OldMoneyAesthetic_table.getSelectedRow(), 8);
        model.setValueAt(tbl_fabric, OldMoneyAesthetic_table.getSelectedRow(), 9);

        JOptionPane.showMessageDialog(this, "Update successfully");
    } else {
        if (OldMoneyAesthetic_table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is Empty");
        } else {
            JOptionPane.showMessageDialog(this, "Please select Single Row For Update");
        }
    }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortActionPerformed

        
    String selectedColumn = (String) sortcolumn.getSelectedItem();
    ArrayList<OldMoneyAestheticModel> data = new ArrayList<>();
    DefaultTableModel tableModel = (DefaultTableModel) OldMoneyAesthetic_table.getModel();

    for (int i = 0; i < tableModel.getRowCount(); i++) {
    int sn = Integer.parseInt(tableModel.getValueAt(i, 0).toString());
    String clothing = tableModel.getValueAt(i, 1).toString();
    String brand = tableModel.getValueAt(i, 2).toString();
    String size = tableModel.getValueAt(i, 3).toString();
    String design = tableModel.getValueAt(i, 4).toString();
    String color = tableModel.getValueAt(i, 5).toString();
    int price = Integer.parseInt(tableModel.getValueAt(i, 6).toString());
    String designer = tableModel.getValueAt(i, 7).toString();
    String occasion = tableModel.getValueAt(i, 8).toString();
    String fabric = tableModel.getValueAt(i, 9).toString();
    
    OldMoneyAestheticModel item = new OldMoneyAestheticModel(sn, clothing, brand, size, design, color, price, designer, occasion, fabric);
    data.add(item);
    }
    
   
    MergeSortTable sorter = new MergeSortTable();
    sorter.sortArrayList(data, selectedColumn);
    
    tableModel.setRowCount(0);
    for (OldMoneyAestheticModel item : data) {
    tableModel.addRow(new Object[]{item.getSn(), item.getClothing(), item.getBrand(), item.getSize(), item.getDesign(), item.getColor(), item.getPrice(), item.getDesigner(), item.getOccasion(), item.getFabric()});

    }    
     JOptionPane.showMessageDialog(this, "Sorted successfully");
   
    }//GEN-LAST:event_jButtonSortActionPerformed

    private void tf_occasionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_occasionActionPerformed
       
    }//GEN-LAST:event_tf_occasionActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    public void getAllTableData() {
        int row = OldMoneyAesthetic_table.getRowCount();

        for (int i = 0; i < row; i++) {
            OldMoneyAestheticModel model = new OldMoneyAestheticModel(
                    Integer.parseInt(
                            OldMoneyAesthetic_table.getValueAt(i, 0).toString()),
                    OldMoneyAesthetic_table.getValueAt(i, 1).toString(),
                    OldMoneyAesthetic_table.getValueAt(i, 2).toString(),
                    OldMoneyAesthetic_table.getValueAt(i, 3).toString(),
                    OldMoneyAesthetic_table.getValueAt(i, 4).toString(),
                    OldMoneyAesthetic_table.getValueAt(i, 5).toString(),
                    Integer.parseInt(
                    OldMoneyAesthetic_table.getValueAt(i, 6).toString()),
                    OldMoneyAesthetic_table.getValueAt(i, 7).toString(),
                    OldMoneyAesthetic_table.getValueAt(i, 8).toString(),
                    OldMoneyAesthetic_table.getValueAt(i, 9).toString()
            );
            clothingList.add(model);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldMoneyAesthetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldMoneyAesthetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldMoneyAesthetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldMoneyAesthetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldMoneyAesthetic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OldMoneyAesthetic_table;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSort;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblClothing;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDesign;
    private javax.swing.JLabel lblDesignerName;
    private javax.swing.JLabel lblFabric;
    private javax.swing.JLabel lblOccassion;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSN;
    private javax.swing.JLabel lblSize;
    private javax.swing.JComboBox<String> sortcolumn;
    private javax.swing.JTextField tf_brand;
    private javax.swing.JTextField tf_clothing;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_design;
    private javax.swing.JTextField tf_designername;
    private javax.swing.JTextField tf_fabric;
    private javax.swing.JTextField tf_occasion;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_size;
    private javax.swing.JTextField tf_sn;
    // End of variables declaration//GEN-END:variables
}
